# ci_pipeline.yml
      
trigger:
  branches:
    include:
      - main
pr: 
 branches:
  include: 
      - main

variables:
- template: /ado_pipelines/variables/pipeline_variables.yml
  
stages:
  - stage: Testing
    jobs: 
      - job: Testing
        displayName: 'Testing'
        condition: or(eq(variables.paramUnitTestingFlag, true), eq(variables.paramIntegrationTestingFlag, true))
 
        steps:

        - bash: |
            echo "##vso[task.prependpath]/home/sys_prd_f1ado/anaconda3/bin"
          displayName: Add Conda to PATH
          condition: succeeded()
          enabled: true

        - bash: |          
            conda init bash
            conda env create --file $(paramCondaDevEnvFilePath)
            source activate $(paramDevEnvName)
            conda deactivate
          displayName: 'Create Conda Dev Environment'
          condition: succeeded()
        
        - bash: |
            source activate $(paramDevEnvName)
            python -m pytest --junitxml=junit/unit-results.xml --doctest-modules $(paramUnitTestingFolderPath) || true
            conda deactivate
          condition: eq(variables.paramUnitTestingFlag, true)
          failOnStderr: 'true'
          displayName: 'Run Unit Tests'

        - bash: |
            source activate $(paramDevEnvName)
            python -m pytest --junitxml=junit/integration-results.xml --doctest-modules $(paramIntegrationTestingFolderPath) || true
            conda deactivate
          condition: eq(variables.paramIntegrationTestingFlag, true)
          failOnStderr: 'true'
          displayName: 'Run Integration Tests'
          
        - task: PublishTestResults@2
          inputs:
            testResultsFiles: 'junit/*-results.xml'
            testRunTitle: 'CI Testing'
            testResultsFormat: 'JUnit'
            failTaskOnFailedTests: true
            publishRunAttachments: false
            mergeTestResults: true
          condition: succeeded()
          displayName: 'Publish Test Results'