# Model deployment pipeline to deploy an AML model to ACI & AKS

pr: none

# Trigger this pipeline on model-train pipeline completion
trigger: none
resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest
  # pipelines:
  # - pipeline: model-train-ci
  #   source: Model-Train-Register-CI # Name of the triggering pipeline
  #   trigger:
  #     branches:
  #       include:
  #       - master

variables:
- template: variables/pipeline_variables.yml

jobs:
- job: "Deploy_Flask_Web_App"
  displayName: "Deploy Flask Web App"
  container: mlops
  timeoutInMinutes: 0
  steps:
  - task: DockerInstaller@0
    displayName: "Install Docker CLI"
    inputs:
      dockerVersion: '17.09.0-ce'
  - task: Docker@2
    displayName: "Build Image & Push Image to ACR"
    inputs:
      containerRegistry: 'acr-connection'
      repository: 'dog_clf_model'
      command: 'buildAndPush'
      Dockerfile: 'src/flask-app/Dockerfile'
  
  