entryScript: score.py
runtime: python
condaFile: ../environments/conda/deployment_environment.yml
extraDockerfileSteps:
schemaFile:
sourceDirectory:
enableGpu: False
baseImage: "mcr.microsoft.com/azureml/intelmpi2018.3-ubuntu16.04:20201113.v1"
baseImageRegistry: