name: pytorch-aml-env
dependencies:
- ipykernel=5.3.4
- matplotlib=3.3.3
- python=3.7.1
- pytorch::pytorch=1.7.0
- pytorch::torchvision=0.8.1
- scipy=1.6.0
- tqdm=4.38.0
- pip:
    - azure-cli==2.18.0
    - azureml-defaults
    - azureml-sdk
    - azureml-widgets
    - python-dotenv==0.15.0
channels:
- conda-forge
- pytorch
