name: pytorch-aml-env
dependencies:
- ipykernel=5.3.4
- python=3.7.1
- pytorch::pytorch=1.7.0
- pytorch::torchvision=0.8.1
- pip:
    - azureml-defaults
    - azureml-sdk
    - azureml-widgets
    - python-dotenv==0.15.0
channels:
- pytorch
