name: dogs_clf_dev_env
channels:
- conda-forge
- pytorch    
dependencies:
- joblib=0.13.2
- matplotlib=3.3.3
- pip=21.0.1
- pytest=6.2.2
- python=3.7.1
- python-dotenv=0.8.2
- pytorch::pytorch=1.7.0
- pytorch::torchvision=0.8.1
- scipy=1.6.0
- tqdm=4.38.0
- pip:
    - azure-cli==2.3.1
    - azure-cognitiveservices-vision-customvision==3.1.0
    - azureml-core==1.26.0
    - azureml-sdk==1.26.0
    - azureml-widgets==1.26.0
    - ipykernel==5.5.5
