apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-clf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-clf-app
  template:
    metadata:
      labels:
        app: dog-clf-app
    spec: 
      containers:
      - image: <ACR_NAME>.azurecr.io/inference/dog_clf_model:1.0.0
        name: dog-clf-container
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dog-clf-service
  name: dog-clf-service
spec:
  ports:
  - targetPort: 5001
    port: 80
    protocol: TCP
  selector:
    app: dog-clf-app
  type: LoadBalancer
