apiVersion: apps/v1
kind: Deployment
metadata:
  name: fowl-pytorch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fowl-pytorch
  template:
    metadata:
      labels:
        app: fowl-pytorch
    spec: 
      containers:
      - image: 3d5545b15c4c49548d3823156fa90536.azurecr.io/inference/fowl-pytorch:1.0
        name: fowl-pytorch
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fowl-pytorch
  name: fowl-pytorch
spec:
  ports:
  - port: 5001
    protocol: TCP
  selector:
    app: fowl-pytorch
  type: LoadBalancer
